baseURL = "http://limograf.com/caldervalleyscouts/"
languageCode = "en-us"
title = "Calder Valley Scouts"
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"
[Params]
  logo = "/images/Scouts_Logo_Stack_White.png"



